title: Edupartage
description: Site de partage de ressources pédagogiques (collège, lycée, agrégation, codes,…)
baseurl: "/gregorysetnikar" # à modifier si ton site est dans un sous-dossier
url: "https://gregorysetnikar.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
