title: Grégory Setnikar - Website
description: Site personnel où je compte déposer mes ressources pédagogiques (collège, lycée, agrégation, codes,…)
baseurl: "/gregorysetnikar" # à modifier si ton site est dans un sous-dossier
url: "https://gregorysetnikar.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
